# Generated by Django 4.1.7 on 2023-04-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100)),
                ('product_line', models.CharField(max_length=100)),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
